print("what is your name?")
name = input()
print("<<<",name + ">>>")
print("(((",name+ ")))")
print("---",name+ "---")
print(":):)",name+ ":):)")
print("###",name+ "###")
print("+++",name+ "+++")
print("~~~",name+ "~~~")
print("===",name+ "===")
