print("name an animal")
animal = input()
print("name a place")
place = input()
print("name a past tense verb")
verb = input()
print("the", animal + " went to the", place + " and", verb + " with his friend the angry turtle")